datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"
  production:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

ebean:
    migration:
      run: true
      generate: true
